#!/usr/bin/env bash
# Public gateway for the OpenManipulator-X panel: a password-protected front
# door, so a QR code can point at one static HTTPS URL.
#
#   internet -> Tailscale Funnel (https, static hostname)
#                   -> nginx :8090  (HTTP Basic Auth, injects the app token)
#                       -> digital_twin_gui.py on 127.0.0.1:8080
#
# The app is deliberately bound to loopback: nginx is then the ONLY way to
# reach it, from the LAN, the tailnet, or the public internet alike. There is
# no path that skips the login.
#
# Idempotent. Run after deploy/install_rpi.sh.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="/etc/omx.env"
HTPASSWD="/etc/omx-web.htpasswd"
SITE="/etc/nginx/sites-available/omx"
WEB_USER="${OMX_WEB_USER:-omx}"
PROXY_PORT="${OMX_PROXY_PORT:-8090}"

say(){ printf "\n\033[1;36m==> %s\033[0m\n" "$*"; }
warn(){ printf "\033[1;33m!!  %s\033[0m\n" "$*"; }

[[ $EUID -eq 0 ]] && { echo "Run as your normal user, not root."; exit 1; }
sudo test -f "$ENV_FILE" || { echo "$ENV_FILE missing - run deploy/install_rpi.sh first."; exit 1; }

say "Installing nginx, htpasswd, qrencode"
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends nginx apache2-utils qrencode

# ------------------------------------------------------------------ password
# Closed by default. If no credentials file exists we create one with a random
# password that is never printed and immediately discarded, so the gateway is
# shut until a human deliberately sets a password. A guessable placeholder
# would be worse than no gateway at all - this thing moves a robot arm.
say "Credentials file"
if sudo test -f "$HTPASSWD"; then
    echo "  keeping existing $HTPASSWD"
else
    LOCK="$(head -c 32 /dev/urandom | base64 | tr -d '\n/+=')"
    sudo htpasswd -bcB "$HTPASSWD" "$WEB_USER" "$LOCK" > /dev/null
    unset LOCK
    warn "Created $HTPASSWD LOCKED - nobody can log in yet."
    warn "Set a real password:  sudo htpasswd -B $HTPASSWD $WEB_USER"
fi
sudo chown root:www-data "$HTPASSWD"
sudo chmod 640 "$HTPASSWD"

# --------------------------------------------------------------------- nginx
say "Writing $SITE"
TOKEN="$(sudo grep -oP 'OMX_WEB_TOKEN=\K.*' "$ENV_FILE")"
sudo tee "$SITE" > /dev/null <<EOF
# Generated by deploy/install_public_gateway.sh - contains OMX_WEB_TOKEN (0640).
server {
    listen $PROXY_PORT default_server;
    listen [::]:$PROXY_PORT default_server;
    server_name _;

    auth_basic           "OpenManipulator-X control";
    auth_basic_user_file $HTPASSWD;

    server_tokens off;
    add_header X-Frame-Options        "DENY"    always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy        "no-referrer" always;

    # Live camera feed, served by omx-camera@.service on :8091. Separate
    # location, separate upstream: if that service is stopped or crashlooping
    # nginx returns 502 for THIS path only and the arm panel is unaffected.
    location /camera/ {
        proxy_pass http://127.0.0.1:8091/;
        proxy_http_version 1.1;
        # MJPEG is an endless multipart response - buffering it would add
        # latency and eventually eat memory, and the default 60s read timeout
        # would cut the feed.
        proxy_buffering     off;
        proxy_read_timeout  3600s;
        proxy_send_timeout  3600s;
        # A dead camera must fail fast so the panel can show "offline"
        # instead of the browser hanging on a connect.
        proxy_connect_timeout 2s;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        # Satisfy the app's own token auth for the authenticated client.
        proxy_set_header Cookie "omx_token=$TOKEN";
        proxy_buffering    off;
        proxy_read_timeout 300s;
    }
}
EOF
sudo chmod 640 "$SITE"
sudo ln -sf "$SITE" /etc/nginx/sites-enabled/omx
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl enable nginx
sudo systemctl restart nginx

# ------------------------------------------------------------------ loopback
say "Binding the app to loopback so nginx is the only door"
if sudo grep -q -- '--bind 127.0.0.1' "$ENV_FILE"; then
    echo "  already bound to 127.0.0.1"
else
    sudo sed -i 's|^OMX_ARGS=.*|OMX_ARGS=--headless --bind 127.0.0.1|' "$ENV_FILE"
    sudo systemctl restart "omx@$USER.service"
    warn "Restarted omx@$USER - the arm is disconnected, press Connect again."
fi

say "Done"
cat <<EOF

  Gateway : http://$(hostname -I | awk '{print $1}'):$PROXY_PORT/   (LAN, plaintext)
  User    : $WEB_USER

  Set the password before exposing anything:
      sudo htpasswd -B $HTPASSWD $WEB_USER

  Then publish it as a static public HTTPS URL with Tailscale Funnel:
      tailscale funnel --bg $PROXY_PORT
      tailscale funnel status

  Funnel first needs, in the Tailscale admin console:
    - DNS page          : enable MagicDNS and HTTPS Certificates
    - Access Controls   : grant this node the "funnel" nodeAttr

EOF
